CREATE TABLE IF NOT EXISTS WEATHER_COMMUNICATION (
    ID INT NOT NULL AUTO_INCREMENT,
    CITY VARCHAR(256) NOT NULL,
    COUNTRY VARCHAR(256) NOT NULL,
    FOR_DATE DATE NOT NULL,
    REQUEST_TIMESTAMP TIMESTAMP NOT NULL,
    
    CONSTRAINT WEATHER_COMMUNICATION_PK PRIMARY KEY (ID)
);